# Generated by Django 2.1.7 on 2020-11-06 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Prince_Institute.Course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Prince_Institute.Course'),
        ),
        migrations.AlterField(
            model_name='result',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Prince_Institute.Course'),
        ),
        migrations.DeleteModel(
            name='technology',
        ),
    ]
