# Generated by Django 2.1.7 on 2020-11-01 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration', models.CharField(max_length=10)),
                ('discription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_fee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Prince_Institute.Course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('mobileno', models.IntegerField()),
                ('father_mob', models.IntegerField()),
                ('dob', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('aadhar', models.IntegerField()),
                ('pcourse', models.CharField(max_length=10)),
                ('photo', models.ImageField(blank=True, upload_to='student_profile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Prince_Institute.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
