# Generated by Django 2.1.7 on 2020-11-17 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Prince_Institute', '0003_auto_20201117_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
