# Generated by Django 2.1.7 on 2020-11-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prince_Institute', '0005_messagerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerequest',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
