# Generated by Django 2.1.7 on 2020-11-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prince_Institute', '0006_auto_20201122_1759'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fee',
            unique_together=set(),
        ),
    ]
